import json
from collections.abc import Iterable
from numbers import Number
from types import NoneType
import gendiff


def flatten(nested_list: Iterable) -> any:
    """
    Yields values from arbitrarily nested list
    :param nested_list: nested list to yield values from
    :return: a value from a list
    """
    for x in nested_list:
        if isinstance(x, Iterable) and not isinstance(x, (str, bytes)):
            yield from flatten(x)
        else:
            yield x


def format_value(input_value: any) -> str:
    """
    Formats value to fit the formatter
    :param input_value: value to be formatted
    :return: formatted string
    """
    if isinstance(input_value, (list, dict)):
        result = "[complex value]"
    elif isinstance(input_value, (bool, NoneType, Number)):
        result = json.dumps(input_value)
    else:
        result = f"'{input_value}'"

    return result


def generate_diff_line(node: dict, path: str) -> str:
    """
    Returns string representation of a node
    :param node:
    :param path:
    :return:
    """
    result = None
    status = gendiff.get_status(node)
    value = format_value(gendiff.get_value(node))
    old_value = (
        format_value(gendiff.get_old_value(node))
        if status == "updated"
        else None
    )
    if status == "new":
        result = f"Property '{path}' was added with value: {value}"
    if status == "removed":
        result = f"Property '{path}' was removed"
    if status == "updated":
        result = f"Property '{path}' was updated. From {old_value} to {value}"
    return result


def format_node_recursively(diff_node: dict) -> map | str:
    """
    Formats node with all its children
    :param diff_node: node from difference generated by gendiff/gendiff.py
    :return: returns str or map object
    """

    def inner(node, path=""):
        result = None
        name = gendiff.get_name(node)
        status = gendiff.get_status(node)
        curr_path = path + "." + name if len(path) > 0 else name
        if not gendiff.has_children(node):
            children = gendiff.get_children(node)
            result = map(lambda _node: inner(_node, curr_path), children)
        elif status != "both":
            result = generate_diff_line(node, curr_path)

        return result

    return inner(diff_node)


def format_as_plain(diff: list) -> str:
    """
    Formats difference in plain textual style
    :param diff: difference between two dicts generated by gendiff/gendiff.py
    :return: string that represents the difference
    """
    diff_formatted = map(format_node_recursively, diff)
    flattened_and_filtered = filter(
        lambda el: el is not None, flatten(diff_formatted)
    )
    return "\n".join(flattened_and_filtered)
